### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by chris-allan** [bcdev/jzarr#10]
At @glencoesoftware we're very excited about the work going on with this library and in collaboration with @ome we are looking to add it to a variety of tools we support pursuant to our collective NGFF [1] goals in biomedical imaging. These tools are both open and closed source. A couple of weeks ago in fe2726e7b3dcab7842b31ffc92a2794b9bd1e4ea license headers were added to all source code specifying GPLv3 or later. The `LICENSE` at the root of the project remains MIT.

Is it the project's intention to relicense versions after `0.3.1` as GPLv3 or later?

 1. https://ngff.openmicroscopy.org/latest/

**Comment by SabineEmbacher** [comment]
Sorry. This project remains under MIT license.
It was a mistake.
I didn't see that my IDE inserted our standard file header instead of the MIT file header.

**Comment by chris-allan** [comment]
Fabulous, great to hear. All the best to everyone for the holidays!
