### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by SabineEmbacher** [bcdev/jzarr#24]
https://zarr.readthedocs.io/en/stable/api/storage.html

- [x] FileSystemStore
- [x] Nested Directory Store (can be a strategy of FileSystemStore) https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.NestedDirectoryStore
- [ ] TempStore https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.TempStore
- [x] Zip Store https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.ZipStore

**Comment by joshmoore** [comment]
Hi @SabineEmbacher, just a few thoughts on this list:
 * `NestedDirectoryStore` and `DirectoryStore` are basically deprecated by `FSStore` which _I think_ should be equivalent for `FileSystemStore`.
 * @DennisHeimbigner rightly brought up (somewhere!) that the ZipStore specs really needs to be written down somewhere. If you have issues implementing it for v2, we might want to go through the process of adding a description to v2.rst; but that should _definitely_ be captured in the spec for v3.

**Comment by SabineEmbacher** [comment]
- [ ] DimensionSeparator implemented in FileSystemStore
- [ ] Allowed separators are "." or "/".
- [ ] If an existing array is opened (old style), whose header (".zarray") does not yet contain a "dimension-separator", it is scanned whether there are already written chunks. If so, their dimension_separator is used.
