### ISSUE TITLE
endianness character present in .zattr for single byte data types

### ISSUE THREAD

**Issue by grlee77** [bcdev/jzarr#25]
cc @joshmoore

While running a [branch of zarr_implementations with jzarr-based read/write tests](https://github.com/joshmoore/zarr_implementations/tree/jzarr) (with jzarr 0.3.2), I encountered the following issue.

The data used in the example in that repository has an 8-bit unsigned integer format. The `.zattr` JSON files created by jzarr currently have the following entry
```
"dtype" : ">u1",
```
but `.zattr` files created by other libraries such as zarr-python, xtensor-zarr and z5py have:
```
"dtype" : "|u1",
```

It seems that the spec indicates that `|` should be used rather than `>` or `<` for data types with a single byte width where there is no endianness.  A similar issue may also be present for `|b1` and `|i1` types, but I have not confirmed that.

**Comment by joshmoore** [comment]
Failing builds can be found in https://github.com/zarr-developers/zarr_implementations/pull/37

**Comment by SabineEmbacher** [comment]
done
