### ISSUE TITLE
is zlib compressor implementation actually a passthrough

### ISSUE THREAD

**Issue by gangchen03** [bcdev/jzarr#37]
Looking at this [zlib compressor implementation code](https://github.com/bcdev/jzarr/blob/master/src/main/java/com/bc/zarr/CompressorFactory.java#L199), the compression implementation seems to be a simple passthrough implemented [here](https://github.com/bcdev/jzarr/blob/006e788fc42d6fbd006d0d3a06ff9e0d1f8db89a/src/main/java/com/bc/zarr/Compressor.java#L43). 
Maybe we should use JDK deflate/inflate classes or Apache common compression library.

**Comment by SabineEmbacher** [comment]
The NullCompressor is a simple passthrough.

The zlib compressor uses the Zip internal Compressor.

![image](https://user-images.githubusercontent.com/209032/204234916-f71e0e97-cf34-459f-a438-5aebcd06da4b.png)

Best Regards
Sabine

**Comment by gangchen03** [comment]
ack. Will test and close the issue.
