### ISSUE TITLE
Move to Maven Central

### ISSUE THREAD

**Issue by joshmoore** [bcdev/jzarr#4]
From https://github.com/zarr-developers/community/issues/15#issuecomment-610007779

 * [ ] prove groupId
 * [x] all dependencies in maven central

**Comment by SabineEmbacher** [comment]
see https://central.sonatype.org/pages/apache-maven.html

**Comment by joshmoore** [comment]
A new tag from https://github.com/zarr-developers/jzarr has now been deployed to https://central.sonatype.com/artifact/dev.zarr/jzarr/0.3.7
