### ISSUE TITLE
Support blosc compression algorithm

### ISSUE THREAD

**Issue by SabineEmbacher** [bcdev/jzarr#8]

**Comment by ymeramees** [comment]
Isn't the solution already existing in blosc branch?

**Comment by SabineEmbacher** [comment]
Yes, but implemented in a way that does not match the planned interface. I want to refactorize this and merge it into the master branch. Users are welcome to use the blosc branch of course, but then they have to expect that the code changes and they have to adapt their implementation to the master version. Once the code is refactored and merged, I will delete the branch.

**Comment by SabineEmbacher** [comment]
The blosc compression is implemented now.
However, this issue remains open because the documentation need to be completed.

If there are people who want to try out the blosc compressor integration and give feedback ... feedback is very welcome.

**Comment by SabineEmbacher** [comment]
Documentation completed.
